**NumPy**, stands for **Numerical Python**, is an open-source Python library consisting of multidimensional and single-dimensional array elements.<br>
It is a standard that computes numerical data in Python. <br>
NumPy is most widely used in almost every domain where numerical computation is required, like science and engineering. <br>
Hence, highly utilized in data science and scientific Python packages, including Pandas, SciPy, Matplotlib, scikit-learn, scikit-image, and many more.

### Why NumPy - Need of NumPy
* NumPy includes a wide range of mathematical functions for basic arithmetic, linear algebra, Fourier analysis, and more.
* NumPy performs numerical operations on large datasets efficiently.
* NumPy supports multi-dimensional arrays, allowing for the representation of complex data structures such as images, sound waves, and tensors in machine learning models.
* It supports the writing of concise and readable code for complex mathematical computations.
* NumPy integrates with other libraries to do scientific computation; these are SciPy (for scientific computing), Pandas (for data manipulation and analysis), and scikit-learn (for machine learning).
* Many scientific and numerical computing libraries and tools are built on top of NumPy.
* Its widespread adoption and stability make it a standard choice for numerical computing tasks.

In [206]:
#### Installing NumPy
! pip install numpy

In [6]:
# Importing NumPy Array
import numpy as np


In [208]:
# Creating an array using np.array() method
arr = np.array([10, 20, 30, 40, 50])

arr

array([10, 20, 30, 40, 50])

In [210]:
arr.dtype

dtype('int32')

In [218]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.int8)
arr

array([10, 20, 30, 40, 50], dtype=int8)

In [220]:
arr[0]

10

In [222]:
arr[1:5]

array([20, 30, 40, 50], dtype=int8)

In [224]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [226]:
arr.shape

(2, 3)

In [236]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [24]:
arr[1,2] = 20
arr

array([[ 1,  2,  3],
       [ 4,  5, 20]])

#### Creating NumPy Array
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw bytes through the use of strings or buffers
6. Use of special library functions (e.g., random)

**Converting Python sequences to NumPy arrays**


In [238]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [240]:
a1D

array([1, 2, 3, 4])

In [242]:
a2D

array([[1, 2],
       [3, 4]])

In [244]:
a3D

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [246]:
np.array([127, 128, 129], dtype=np.int8) # Overflow Wrror

C:\Users\jlakh\AppData\Local\Temp\ipykernel_20780\1953225749.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8) # Overflow Wrror
C:\Users\jlakh\AppData\Local\Temp\ipykernel_20780\1953225749.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([127, 128, 129], dtype=np.int8) # Overflow Wrror


array([ 127, -128, -127], dtype=int8)

**Intrinsic NumPy array creation functions**
> **1D array creation functions**

In [248]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [250]:
np.arange(5, 20, dtype=float)


array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.])

In [256]:
np.arange(2, 1, -0.1) # (start, end, step)

array([2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1])

In [47]:
np.linspace(1., 4., 6)  # (start, end , number of parts)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

> **2D array creation functions**

In [260]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [262]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [264]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

> **general ndarray creation functions**

In [266]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [268]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [270]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [276]:
np.ones((3,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [278]:
np.random.randint(10, 20, size= (3,3))

array([[12, 18, 13],
       [12, 14, 10],
       [19, 10, 18]])

In [67]:
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

numpy.indices will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension:

In [70]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

#### Reshape and flatten arrays

In [280]:
arr = np.arange(27)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [282]:
arr.size, arr.shape

(27, (27,))

In [290]:
arr.reshape((3,9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [294]:
arr = arr.reshape((3,9))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [296]:
arr.size, arr.shape

(27, (3, 9))

In [298]:
arr.reshape((3,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [300]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [302]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [304]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [306]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### NumPy Axis

In [309]:
# 1D array: [axis0] 
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [317]:
# 2D array : [axis0, axi1]
arr = np.random.randint(0,3, size = (3,3))
arr

array([[1, 2, 0],
       [1, 1, 1],
       [0, 0, 2]])

In [319]:
arr.sum()

8

In [321]:
arr.sum(axis=0)

array([2, 3, 3])

In [323]:
arr.sum(axis=1)

array([3, 3, 2])

In [325]:
arr

array([[1, 2, 0],
       [1, 1, 1],
       [0, 0, 2]])

In [327]:
arr.T

array([[1, 1, 0],
       [2, 1, 0],
       [0, 1, 2]])

In [126]:
arr.size

9

In [329]:
arr.ndim

2

In [130]:
arr.shape

(3, 3)

In [331]:
arr = np.array([[1,2,3], [6,5,8], [7,9,4]])
arr

array([[1, 2, 3],
       [6, 5, 8],
       [7, 9, 4]])

In [335]:
arr.argmax()

7

In [337]:
arr.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [339]:
arr.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [341]:
arr = np.array([1,4,2,8,3])
arr

array([1, 4, 2, 8, 3])

In [343]:
arr.argmax()

3

In [345]:
arr.argmin()

0

In [347]:
arr.argsort()

array([0, 2, 4, 1, 3], dtype=int64)

In [355]:
arr[[0, 2, 4, 1, 3]]

array([1, 2, 3, 4, 8])

#### Arithmetic Operations

In [357]:
a1 = np.array([[1, 2, 1],
               [3, 2, 2],
               [1, 1, 3]])
a1

array([[1, 2, 1],
       [3, 2, 2],
       [1, 1, 3]])

In [359]:
a2 = np.array([[2, 1, 1],
               [1, 3, 2],
               [1, 2, 1]])
a2

array([[2, 1, 1],
       [1, 3, 2],
       [1, 2, 1]])

In [361]:
a1 + a2

array([[3, 3, 2],
       [4, 5, 4],
       [2, 3, 4]])

In [363]:
a1 - a2

array([[-1,  1,  0],
       [ 2, -1,  0],
       [ 0, -1,  2]])

In [365]:
a1 * a2

array([[2, 2, 1],
       [3, 6, 4],
       [1, 2, 3]])

In [367]:
a1

array([[1, 2, 1],
       [3, 2, 2],
       [1, 1, 3]])

In [371]:
a1+5

array([[6, 7, 6],
       [8, 7, 7],
       [6, 6, 8]])

In [373]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.73205081]])

In [375]:
a1.sum()

16

In [377]:
a1.min()

1

In [379]:
a1.min(axis=0)

array([1, 1, 1])

In [381]:
a1.min(axis=1)

array([1, 2, 1])

In [389]:
a1

array([[1, 2, 1],
       [3, 2, 2],
       [1, 1, 3]])

In [387]:
np.where(a1>2)

(array([1, 2], dtype=int64), array([0, 2], dtype=int64))

In [405]:
type(np.where(a1>2))

tuple